package com.jike.mobile.sna.common.thrift;
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ReturnType implements org.apache.thrift.TEnum {
  SUCCESS(0),
  DBNAME_USED(-1),
  DBSIZE_EXCEEDED(-2),
  DB_NONEXIST(-3),
  INVALID_KEY_OR_VALUE(-4),
  DB_NONSPACE(-5),
  VALUE_NONEXIST(-6),
  SEND_MSG_FAIL(-7),
  GET_CLIENT_FAIL(-8),
  PUT_TAIR_FAIL(-9),
  OTHER(-100);

  private final int value;

  private ReturnType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ReturnType findByValue(int value) { 
    switch (value) {
      case 0:
        return SUCCESS;
      case -1:
        return DBNAME_USED;
      case -2:
        return DBSIZE_EXCEEDED;
      case -3:
        return DB_NONEXIST;
      case -4:
        return INVALID_KEY_OR_VALUE;
      case -5:
        return DB_NONSPACE;
      case -6:
        return VALUE_NONEXIST;
      case -7:
        return SEND_MSG_FAIL;
      case -8:
        return GET_CLIENT_FAIL;
      case -9:
        return PUT_TAIR_FAIL;
      case -100:
        return OTHER;
      default:
        return null;
    }
  }
}
